/*
 * Copyright (c) 2025 Lynne <dev@lynne.ee>
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

GetBitContext gb;

int apv_read_vlc(int k_param)
{
    uint next_bits = show_bits(gb, APV_VLC_LUT_BITS);
    SingleCLUTEntry ent = single_lut[k_param][next_bits];

    if (ent.more != 0) {
        skip_bits(gb, ent.consume);

        next_bits = show_bits(gb, 16);
        int leading_zeroes = 15 - findMSB(next_bits);

        if (leading_zeroes == 0)
            return APV_MAX_TRANS_COEFF + 1;

        skip_bits(gb, leading_zeroes + 1);

        return (2 << k_param) +
               ((1 << leading_zeroes) - 1) * (1 << k_param) +
               int(get_bits(gb, leading_zeroes + k_param));
    }

    skip_bits(gb, ent.consume);
    return int(ent.result);
}

int prev_dc;
int prev_k_dc;
int prev_k_level;
int prev_1st_ac_level;

const ivec2 zigzag[64] = {
    ivec2(0, 0), ivec2(1, 0), ivec2(0, 1), ivec2(0, 2),
    ivec2(1, 1), ivec2(2, 0), ivec2(3, 0), ivec2(2, 1),
    ivec2(1, 2), ivec2(0, 3), ivec2(0, 4), ivec2(1, 3),
    ivec2(2, 2), ivec2(3, 1), ivec2(4, 0), ivec2(5, 0),
    ivec2(4, 1), ivec2(3, 2), ivec2(2, 3), ivec2(1, 4),
    ivec2(0, 5), ivec2(0, 6), ivec2(1, 5), ivec2(2, 4),
    ivec2(3, 3), ivec2(4, 2), ivec2(5, 1), ivec2(6, 0),
    ivec2(7, 0), ivec2(6, 1), ivec2(5, 2), ivec2(4, 3),
    ivec2(3, 4), ivec2(2, 5), ivec2(1, 6), ivec2(0, 7),
    ivec2(1, 7), ivec2(2, 6), ivec2(3, 5), ivec2(4, 4),
    ivec2(5, 3), ivec2(6, 2), ivec2(7, 1), ivec2(7, 2),
    ivec2(6, 3), ivec2(5, 4), ivec2(4, 5), ivec2(3, 6),
    ivec2(2, 7), ivec2(3, 7), ivec2(4, 6), ivec2(5, 5),
    ivec2(6, 4), ivec2(7, 3), ivec2(7, 4), ivec2(6, 5),
    ivec2(5, 6), ivec2(4, 7), ivec2(5, 7), ivec2(6, 6),
    ivec2(7, 5), ivec2(7, 6), ivec2(6, 7), ivec2(7, 7),
};

void apv_decode_block(ivec2 pos, uint comp)
{
    int dc_coeff;
    int abs_diff = apv_read_vlc(prev_k_dc);

    if (abs_diff != 0) {
        if (get_bit(gb))
            dc_coeff = prev_dc - abs_diff;
        else
            dc_coeff = prev_dc + abs_diff;
    } else {
        dc_coeff = prev_dc;
    }

    if (dc_coeff < APV_MIN_TRANS_COEFF ||
        dc_coeff > APV_MAX_TRANS_COEFF)
        return;

    imageStore(dst[comp], pos, ivec4(dc_coeff));
    prev_dc   = dc_coeff;
    prev_k_dc = min(abs_diff >> 1, 5);

    /* ACs */
    int scan_pos   = 1;
    int first_ac   = 1;
    int prev_level = prev_1st_ac_level;
    int prev_run   = 0;

    do {
        int coeff_zero_run;

        int k_param = clamp(prev_run >> 2, 0, 2);
        coeff_zero_run = apv_read_vlc(k_param);

        if (coeff_zero_run > APV_BLK_COEFFS - scan_pos)
            return;

        for (int i = 0; i < coeff_zero_run; i++) {
            //            coeff[scan_pos] = 0;
            ++scan_pos;
        }
        prev_run = coeff_zero_run;

        if (scan_pos < APV_BLK_COEFFS) {
            int abs_ac_coeff_minus1;
            int level;

            k_param = clamp(prev_level >> 2, 0, 4);
            abs_ac_coeff_minus1 = apv_read_vlc(k_param);
            bool sign_ac_coeff = get_bit(gb);

            if (sign_ac_coeff)
                level = -abs_ac_coeff_minus1 - 1;
            else
                level = abs_ac_coeff_minus1 + 1;

            if (level < APV_MIN_TRANS_COEFF || level > APV_MAX_TRANS_COEFF)
                return;

            imageStore(dst[comp], pos + zigzag[scan_pos], ivec4(level));

            prev_level = abs_ac_coeff_minus1 + 1;
            if (first_ac != 0) {
                prev_1st_ac_level = prev_level;
                first_ac = 0;
            }

            ++scan_pos;
        }
    } while (scan_pos < APV_BLK_COEFFS);
}

void main(void)
{
    const ivec2 tile_pos = ivec2(gl_WorkGroupID.xy);
    const uint comp_idx = uint(gl_WorkGroupID.z);

    /* EC state */
    prev_dc = 0;
    prev_k_dc = 5;
    prev_1st_ac_level = 0;

    const uvec2 tile_bs = tile_offset[comp_idx][tile_pos.y][tile_pos.x];
    init_get_bits(gb, u8buf(tile_data + tile_bs.x), int(tile_bs.y));

    ivec2 sub_shift = comp_idx == 0 ? ivec2(0) : log2_chroma_sub;
    ivec2 tile_start = ivec2(tile_col[tile_pos.x], tile_row[tile_pos.y]);
    ivec2 tile_dim = ivec2(tile_col[tile_pos.x + 1],
                           tile_row[tile_pos.y + 1]) - tile_start;
    ivec2 tile_mb_dim = tile_dim / APV_MB_SIZE;
    ivec2 blk_mb_dim = ivec2(2, 2) >> sub_shift;
    float bd_shift = bit_depth + 3 - 5;

    ivec2 mb, blk;
    for (mb.y = 0; mb.y < tile_mb_dim.y; mb.y++) {
        for (mb.x = 0; mb.x < tile_mb_dim.x; mb.x++) {
            for (blk.y = 0; blk.y < blk_mb_dim.y; blk.y++) {
                for (blk.x = 0; blk.x < blk_mb_dim.x; blk.x++) {
                    ivec2 pos = (APV_MB_SIZE*mb +
                                 APV_TR_SIZE*blk + tile_start) >> sub_shift;

                    apv_decode_block(pos, comp_idx);
                }
            }
        }
    }
}
