/*
 * Copyright (c) 2025 Lynne <dev@lynne.ee>
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

TYPE read_data(int off)
{
    TYPE p = pd.data[off];
    if (big_endian > 0)
        p = TYPE_REVERSE(p);
    return p;
}

void main(void)
{
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (!IS_WITHIN(pos, imageSize(dst[0])))
        return;

    const ivec4 fmt_lut = components == 1 ? ivec4(0) : ivec4(2, 0, 1, 3);
    for (int i = 0; i < components; i++) {
        TYPE val = read_data((pos.y*imageSize(dst[0]).x + pos.x)*components + i);
        imageStore(dst[fmt_lut[i]], pos, TYPE_VEC(val >> shift));
    }
}
